name: Matrixed Tests

on: 
  workflow_dispatch

jobs:
  ubuntu_tests:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.9', '3.12']  # TODO: Add 3.13 when it is released
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: pip install --upgrade --upgrade-strategy eager -e '.[datadriven, test]'
    - name: Run tests
      run: python -m tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  macos_13_tests:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.9', '3.12']  # TODO: Add 3.13 when it is released
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: pip install --upgrade --upgrade-strategy eager -e '.[datadriven, test]'
    - name: Run tests
      run: python -m tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  macos_latest_tests:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.9', '3.12']  # TODO: Add 3.13 when it is released
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: pip install --upgrade --upgrade-strategy eager -e '.[datadriven, test]'
    - name: Run tests
      run: python -m tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  windows_tests:
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.9', '3.12']  # TODO: Add 3.13 when it is released
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: pip install --upgrade --upgrade-strategy eager -e '.[datadriven, test]'
    - name: Run tests
      run: python -m tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml