name: Matrixed Tests

on: 
  workflow_dispatch

jobs:
  run_tests:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.12']  # TODO: Add 3.13 when it is released
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: pip install --upgrade --upgrade-strategy eager -e '.[datadriven, test]'
    - name: Run tests
      run: python -m tests
    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version }} == '3.12' && ${{ matrix.os }} == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml